export const mockDevices = [
  {
    id: 1,
    deviceId: "d2c25338-5f5e-4a7d-9554-398e6730cd7f",
    deviceType: "camera",
    user: { id: 1, email: "user@example.com" },
    deviceName: "Living Room Camera",
    ipAddress: "192.168.1.100",
    location: "Living Room",
    cameraEnabled: true,
    recordingEnabled: true,
    permissionLevel: "admin",
    lastActiveAt: new Date(),
    createdAt: new Date(Date.now() - 7200000),
    updatedAt: new Date(),
  },
  {
    id: 2,
    deviceId: "7f8e9d2c-6b3a-4f5d-8e7c-9b2a1c3d4e5f",
    deviceType: "laptop",
    user: { id: 1, email: "user@example.com" },
    deviceName: "MacBook Pro",
    ipAddress: "192.168.1.101",
    location: "Office",
    cameraEnabled: true,
    recordingEnabled: false,
    permissionLevel: "user",
    lastActiveAt: new Date(Date.now() - 3600000),
    createdAt: new Date(Date.now() - 5400000),
    updatedAt: new Date(),
  },
  {
    id: 3,
    deviceId: "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
    deviceType: "smartphone",
    user: { id: 1, email: "user@example.com" },
    deviceName: "iPhone 13",
    ipAddress: "192.168.1.102",
    location: "Mobile",
    cameraEnabled: true,
    recordingEnabled: false,
    permissionLevel: "user",
    lastActiveAt: new Date(Date.now() - 7200000),
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(),
  },
  {
    id: 4,
    deviceId: "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
    deviceType: "tablet",
    user: { id: 1, email: "user@example.com" },
    deviceName: "iPad Pro",
    ipAddress: "192.168.1.103",
    location: "Living Room",
    cameraEnabled: true,
    recordingEnabled: true,
    permissionLevel: "user",
    lastActiveAt: new Date(),
    createdAt: new Date(Date.now() - 1800000),
    updatedAt: new Date(),
  },
  {
    id: 5,
    deviceId: "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
    deviceType: "monitor",
    user: { id: 1, email: "user@example.com" },
    deviceName: "Security Monitor",
    ipAddress: "192.168.1.104",
    location: "Front Door",
    cameraEnabled: true,
    recordingEnabled: false,
    permissionLevel: "guest",
    lastActiveAt: new Date(Date.now() - 1800000),
    createdAt: new Date(Date.now() - 900000),
    updatedAt: new Date(),
  },
];
export const mockActivities = [
  {
    id: 1,
    deviceId: "d2c25338-5f5e-4a7d-9554-398e6730cd7f",
    deviceName: "Living Room Camera",
    type: "Motion Detected",
    timestamp: new Date(),
    clipUrl: "/clips/living-room-1.mp4",
    motionArea: { x: 320, y: 240, width: 100, height: 100 },
    notificationSent: true,
    severity: "high",
  },
  {
    id: 2,
    deviceId: "7f8e9d2c-6b3a-4f5d-8e7c-9b2a1c3d4e5f",
    deviceName: "Front Door Camera",
    type: "Camera Offline",
    timestamp: new Date(Date.now() - 1800000),
    notificationSent: true,
    severity: "medium",
  },
  {
    id: 3,
    deviceId: "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
    deviceName: "Kitchen Camera",
    type: "Motion Detected",
    timestamp: new Date(Date.now() - 3600000),
    clipUrl: "/clips/kitchen-1.mp4",
    motionArea: { x: 100, y: 150, width: 80, height: 80 },
    notificationSent: true,
    severity: "low",
  },
];
